# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    # External services that we want to run together with our job  
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:12
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: root
          POSTGRES_DB: simple_bank
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5 #magic___^_^___line #magic___^_^___line
        ports:
        - 5439:5432 # Map host port 5432 to container port 5432
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    - name: Check out code code into Go module directoy
      uses: actions/checkout@v3

    - name: Run migrations
      run: make migrateup

    - name: Test
      run: make test
